[package]
name = "thread_nocrypt_rand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.17.1"
rand = "0.8.5"
rand_xoshiro = "0.6.0"

[dev-dependencies]
rayon = "1.7.0"

